### ISSUE TITLE
Not compatible with crystal 1.15?

### ISSUE THREAD

**Issue by carlhoerberg** [ysbaddaden/gc#32]
Got this when trying to compile with crystal 1.15. I haven't looked into it but I guess the default GC module has been given a new method: `sig_suspend`

```
In /usr/share/crystal/src/process.cr:280:36

 280 | pid = Crystal::System::Process.spawn(command_args, env, clear_env, fork_input, fork_output, fork_error, chdir.try &.to_s)
                                      ^----
Error: instantiating 'Crystal::System::Process.spawn(Array(String), Nil, Bool, IO::FileDescriptor+, IO::FileDescriptor+, IO::FileDescriptor+, Nil)'


In /usr/share/crystal/src/crystal/system/unix/process.cr:246:16

 246 | pid = self.fork(will_exec: true)
                  ^---
Error: instantiating 'Crystal::System::Process.fork(will_exec: Bool)'


In /usr/share/crystal/src/crystal/system/unix/process.cr:185:55

 185 | LibC.sigdelset(pointerof(newmask), System::Thread.sig_suspend)
                                                         ^----------
Error: instantiating 'Crystal::System::Thread.sig_suspend()'


In /usr/share/crystal/src/crystal/system/unix/pthread.cr:273:10

 273 | GC.sig_suspend
          ^----------
Error: undefined method 'sig_suspend' for GC:Module

GC:Module trace:

  /usr/share/crystal/src/crystal/system/unix/pthread.cr:273

          GC.sig_suspend

```

**Comment by ysbaddaden** [comment]
The GC interface evolved in https://github.com/crystal-lang/crystal/commit/8f26137180b0f44257b88e71bab8b91ebbdffd45

I shall update it :+1:

**Comment by ysbaddaden** [comment]
Actually, it shouldn't fail as we're testing whether the `GC.sig_suspend` method is defined:
https://github.com/crystal-lang/crystal/commit/57017f6de66d88436bd80862c23a1ed0bff69648

But I guess `Module.responds_to?` is wrong.

**Comment by ysbaddaden** [comment]
Yeah: this doesn't work:

```crystal
module Foo; end

if Foo.responds_to?(:something)
  Foo.something
  # ^- no such method Foo.something
end
```

But this works :facepalm: 

```crystal
module Foo; end

if (foo = Foo).responds_to?(:something)
  foo.something
  # ^- skipped
end
```

**Comment by Sija** [comment]
This should be fixed now.
